apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-control-plane
  labels:
    app.kubernetes.io/name: nexuslog-control-plane
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: nexuslog-control-plane
    app.kubernetes.io/instance: {{ .Release.Name }}
