package notification

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"
)

// EmailSender sends email notifications.
type EmailSender interface {
	Send(config EmailConfig, subject, body, to string) error
}

// DingTalkMessageSender sends DingTalk notifications.
type DingTalkMessageSender interface {
	Send(config DingTalkConfig, alert AlertMessage) error
}

// WebhookMessageSender sends generic webhook notifications.
type WebhookMessageSender interface {
	SendAlert(config WebhookConfig, payload DispatchPayload) error
}

// DispatchPayload describes a notification generated by alert evaluation.
type DispatchPayload struct {
	Title               string `json:"title"`
	Detail              string `json:"detail,omitempty"`
	Severity            string `json:"severity,omitempty"`
	FiredAt             string `json:"fired_at,omitempty"`
	TenantID            string `json:"tenant_id,omitempty"`
	RuleID              string `json:"rule_id,omitempty"`
	ResourceThresholdID string `json:"resource_threshold_id,omitempty"`
	SourceID            string `json:"source_id,omitempty"`
	AgentID             string `json:"agent_id,omitempty"`
}

// DeliveryResult describes a single recipient delivery outcome.
type DeliveryResult struct {
	Recipient string `json:"recipient,omitempty"`
	Success   bool   `json:"success"`
	Error     string `json:"error,omitempty"`
}

// DispatchChannelResult describes the send outcome for one notification channel.
type DispatchChannelResult struct {
	ChannelID   string           `json:"channel_id"`
	ChannelName string           `json:"channel_name"`
	ChannelType string           `json:"channel_type"`
	Status      string           `json:"status"`
	Success     bool             `json:"success"`
	Error       string           `json:"error,omitempty"`
	Deliveries  []DeliveryResult `json:"deliveries,omitempty"`
}

// DispatchSummary aggregates results for a notification attempt.
type DispatchSummary struct {
	Status             string                  `json:"status"`
	AttemptedChannels  int                     `json:"attempted_channels"`
	SuccessfulChannels int                     `json:"successful_channels"`
	LastAttemptAt      string                  `json:"last_attempt_at"`
	Results            []DispatchChannelResult `json:"results,omitempty"`
}

// Dispatcher resolves configured channels and dispatches alert notifications.
type Dispatcher struct {
	repo           *ChannelRepository
	emailSender    EmailSender
	dingTalkSender DingTalkMessageSender
	webhookSender  WebhookMessageSender
}

// NewDispatcher creates a dispatcher with concrete senders.
func NewDispatcher(repo *ChannelRepository, emailSender *SMTPSender, dingTalkSender *DingTalkSender) *Dispatcher {
	if emailSender == nil {
		emailSender = NewSMTPSender()
	}
	if dingTalkSender == nil {
		dingTalkSender = NewDingTalkSender()
	}
	return &Dispatcher{
		repo:           repo,
		emailSender:    emailSender,
		dingTalkSender: dingTalkSender,
		webhookSender:  NewWebhookSender(),
	}
}

// Dispatch sends a notification to the configured channels.
func (d *Dispatcher) Dispatch(ctx context.Context, tenantID string, rawChannelIDs json.RawMessage, payload DispatchPayload) (*DispatchSummary, error) {
	if d == nil || d.repo == nil {
		return nil, fmt.Errorf("notification dispatcher is not configured")
	}

	channelIDs, err := parseChannelIDs(rawChannelIDs)
	if err != nil {
		return nil, fmt.Errorf("parse notification channels: %w", err)
	}

	summary := &DispatchSummary{
		Status:        "skipped",
		LastAttemptAt: time.Now().UTC().Format(time.RFC3339),
		Results:       make([]DispatchChannelResult, 0, len(channelIDs)),
	}
	if len(channelIDs) == 0 {
		summary.Status = "no_channels"
		return summary, nil
	}

	for _, channelID := range channelIDs {
		result := d.dispatchChannel(ctx, strings.TrimSpace(tenantID), channelID, payload)
		summary.Results = append(summary.Results, result)
		if result.Status != "skipped" {
			summary.AttemptedChannels++
		}
		if result.Success {
			summary.SuccessfulChannels++
		}
	}

	switch {
	case summary.AttemptedChannels == 0:
		summary.Status = "skipped"
	case summary.SuccessfulChannels == summary.AttemptedChannels:
		summary.Status = "sent"
	case summary.SuccessfulChannels > 0:
		summary.Status = "partial"
	default:
		summary.Status = "failed"
	}
	return summary, nil
}

func (d *Dispatcher) dispatchChannel(ctx context.Context, tenantID, channelID string, payload DispatchPayload) DispatchChannelResult {
	result := DispatchChannelResult{
		ChannelID: channelID,
		Status:    "failed",
	}
	if strings.TrimSpace(channelID) == "" {
		result.Status = "skipped"
		result.Error = "channel id is empty"
		return result
	}

	channel, err := d.repo.GetChannel(ctx, tenantID, channelID)
	if err != nil {
		result.Error = err.Error()
		return result
	}
	result.ChannelName = channel.Name
	result.ChannelType = channel.Type
	if !channel.Enabled {
		result.Status = "skipped"
		result.Error = "channel is disabled"
		return result
	}

	switch strings.ToLower(strings.TrimSpace(channel.Type)) {
	case "email":
		return d.dispatchEmail(channel, payload)
	case "dingtalk":
		return d.dispatchDingTalk(channel, payload)
	case "webhook":
		return d.dispatchWebhook(channel, payload)
	default:
		result.Status = "skipped"
		result.Error = fmt.Sprintf("unsupported channel type: %s", channel.Type)
		return result
	}
}

func (d *Dispatcher) dispatchEmail(channel Channel, payload DispatchPayload) DispatchChannelResult {
	result := DispatchChannelResult{
		ChannelID:   channel.ID,
		ChannelName: channel.Name,
		ChannelType: channel.Type,
		Status:      "failed",
	}
	cfg, err := ParseEmailConfig(channel.Config)
	if err != nil {
		result.Error = err.Error()
		return result
	}
	if len(cfg.Recipients) == 0 {
		result.Error = "email channel has no recipients configured"
		return result
	}

	subject := buildEmailSubject(payload)
	body := buildEmailBody(payload)
	successCount := 0
	for _, recipient := range cfg.Recipients {
		delivery := DeliveryResult{Recipient: recipient}
		if err := d.emailSender.Send(cfg, subject, body, recipient); err != nil {
			delivery.Error = err.Error()
		} else {
			delivery.Success = true
			successCount++
		}
		result.Deliveries = append(result.Deliveries, delivery)
	}

	switch {
	case successCount == len(cfg.Recipients):
		result.Status = "sent"
		result.Success = true
	case successCount > 0:
		result.Status = "partial"
		result.Success = true
		result.Error = "some recipients failed"
	default:
		result.Status = "failed"
		result.Error = "all recipients failed"
	}
	return result
}

func (d *Dispatcher) dispatchDingTalk(channel Channel, payload DispatchPayload) DispatchChannelResult {
	result := DispatchChannelResult{
		ChannelID:   channel.ID,
		ChannelName: channel.Name,
		ChannelType: channel.Type,
		Status:      "failed",
	}
	cfg, err := ParseDingTalkConfig(channel.Config)
	if err != nil {
		result.Error = err.Error()
		return result
	}
	message := AlertMessage{
		Title:    payload.Title,
		Detail:   payload.Detail,
		RuleID:   firstNonEmpty(payload.RuleID, payload.ResourceThresholdID),
		Severity: payload.Severity,
		FiredAt:  normalizeFiredAt(payload.FiredAt),
	}
	if err := d.dingTalkSender.Send(cfg, message); err != nil {
		result.Error = err.Error()
		return result
	}
	result.Status = "sent"
	result.Success = true
	return result
}

func (d *Dispatcher) dispatchWebhook(channel Channel, payload DispatchPayload) DispatchChannelResult {
	result := DispatchChannelResult{
		ChannelID:   channel.ID,
		ChannelName: channel.Name,
		ChannelType: channel.Type,
		Status:      "failed",
	}
	cfg, err := ParseWebhookConfig(channel.Config)
	if err != nil {
		result.Error = err.Error()
		return result
	}
	if err := d.webhookSender.SendAlert(cfg, payload); err != nil {
		result.Error = err.Error()
		return result
	}
	result.Status = "sent"
	result.Success = true
	return result
}

func parseChannelIDs(raw json.RawMessage) ([]string, error) {
	if len(raw) == 0 || strings.TrimSpace(string(raw)) == "" {
		return nil, nil
	}

	var ids []string
	if err := json.Unmarshal(raw, &ids); err == nil {
		return normalizeStringList(ids), nil
	}

	var items []interface{}
	if err := json.Unmarshal(raw, &items); err != nil {
		return nil, err
	}
	ids = make([]string, 0, len(items))
	for _, item := range items {
		if text, ok := item.(string); ok {
			ids = append(ids, text)
		}
	}
	return normalizeStringList(ids), nil
}

func normalizeStringList(values []string) []string {
	seen := make(map[string]struct{}, len(values))
	normalized := make([]string, 0, len(values))
	for _, value := range values {
		trimmed := strings.TrimSpace(value)
		if trimmed == "" {
			continue
		}
		if _, exists := seen[trimmed]; exists {
			continue
		}
		seen[trimmed] = struct{}{}
		normalized = append(normalized, trimmed)
	}
	return normalized
}

func buildEmailSubject(payload DispatchPayload) string {
	severity := strings.ToUpper(strings.TrimSpace(payload.Severity))
	if severity == "" {
		severity = "INFO"
	}
	title := strings.TrimSpace(payload.Title)
	if title == "" {
		title = "NexusLog Alert"
	}
	return fmt.Sprintf("[NexusLog][%s] %s", severity, title)
}

func buildEmailBody(payload DispatchPayload) string {
	lines := []string{
		fmt.Sprintf("标题: %s", firstNonEmpty(strings.TrimSpace(payload.Title), "NexusLog Alert")),
		fmt.Sprintf("级别: %s", firstNonEmpty(strings.TrimSpace(payload.Severity), "unknown")),
		fmt.Sprintf("触发时间: %s", normalizeFiredAt(payload.FiredAt)),
	}
	if detail := strings.TrimSpace(payload.Detail); detail != "" {
		lines = append(lines, fmt.Sprintf("详情: %s", detail))
	}
	if tenantID := strings.TrimSpace(payload.TenantID); tenantID != "" {
		lines = append(lines, fmt.Sprintf("租户 ID: %s", tenantID))
	}
	if ruleID := strings.TrimSpace(payload.RuleID); ruleID != "" {
		lines = append(lines, fmt.Sprintf("规则 ID: %s", ruleID))
	}
	if thresholdID := strings.TrimSpace(payload.ResourceThresholdID); thresholdID != "" {
		lines = append(lines, fmt.Sprintf("阈值 ID: %s", thresholdID))
	}
	if agentID := strings.TrimSpace(payload.AgentID); agentID != "" {
		lines = append(lines, fmt.Sprintf("Agent ID: %s", agentID))
	}
	if sourceID := strings.TrimSpace(payload.SourceID); sourceID != "" {
		lines = append(lines, fmt.Sprintf("来源: %s", sourceID))
	}
	return strings.Join(lines, "\n")
}

func normalizeFiredAt(value string) string {
	if trimmed := strings.TrimSpace(value); trimmed != "" {
		return trimmed
	}
	return time.Now().UTC().Format(time.RFC3339)
}

func firstNonEmpty(values ...string) string {
	for _, value := range values {
		if trimmed := strings.TrimSpace(value); trimmed != "" {
			return trimmed
		}
	}
	return ""
}
