# NexusLog Kubernetes Base Kustomization
# 基础 Kustomize 配置，定义所有环境共享的资源
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../namespaces/
  - ../rbac/
  - ../network-policies/
  - ../storageclasses/
  # 应用服务
  - frontend-console.yaml
  - control-plane.yaml
  - api-service.yaml
  - bff-service.yaml
  - health-worker.yaml
  - data-services.yaml

commonLabels:
  app.kubernetes.io/part-of: nexuslog
  app.kubernetes.io/managed-by: kustomize
